### ISSUE TITLE
Asimba IDP list form - FriendlyName field double view

### ISSUE THREAD

**Issue by dmogn** [GluuFederation/gluu-Asimba#10]
screenshot:
![asimba_idp_list_form](https://cloud.githubusercontent.com/assets/14166017/13814514/53b40c04-eb65-11e5-8803-4f485f4c1390.jpg)

**Comment by mzico** [comment]
@dmogn : Just to share.... previously we used to customize the discovery page with 'saml_selector.jsp' file, it's inside 'ui/sso/authn/saml2/saml_selector.jsp'

**Comment by dmogn** [comment]
Thanks, @mzico.

**Comment by dmogn** [comment]
Fixed.
