### ISSUE TITLE
RDN to store asimba configuration

### ISSUE THREAD

**Issue by yurem** [GluuFederation/gluu-Asimba#11]
Asimba stores all information under:
DN: ou=oxasimba,ou=configuration,inum=<appliance_inum>,ou=appliances,o=gluu
![screenshot_1](https://cloud.githubusercontent.com/assets/6104200/13880864/00bc8544-ed27-11e5-96a3-bcaca85bfecc.png)

I think it should split this configuration into 2 parts.
1) Store in: DN: ou=oxasimba,ou=configuration,inum=<appliance_inum>,ou=appliances,o=gluu
application specific base settings needt to application startup.
2) Store IDP, selectors, etc.. settings under: ou=oxasimba,o=<org_inum>,o=gluu

It will be generic method of storing data in OX projects

@nynymike , What do you think?

**Comment by nynymike** [comment]
yes, I totally agree. We should split the configuration data from the application data.

**Comment by dmogn** [comment]
Done.
