### ISSUE TITLE
Read LDAP connection configuration from ox-ldap.properties

### ISSUE THREAD

**Issue by dmogn** [GluuFederation/gluu-Asimba#12]
- Check oxasimba-ldap.properties availability.
- Read ox-ldap.properties if isn't.
- Delete oxasimba-ldap.properties creation from the installer.

**Comment by dmogn** [comment]
Yuriy Movchan: https://github.com/GluuFederation/oxTrust/blob/master/openid-auth-client/src/main/java/org/gluu/oxauth/client/conf/Configuration.java#L111
Yuriy Movchan:   String ldapConfigurationFileName = "oxasimba-ldap.properties";
  FileConfiguration fileConfiguration = loadLdapConfiguration(ldapConfigurationFileName, false);
  if (fileConfiguration == null) {
   ldapConfigurationFileName = "ox-ldap.properties";
   fileConfiguration = loadLdapConfiguration(ldapConfigurationFileName, true);
  }

**Comment by nynymike** [comment]
oxauth-ldap.properties should be fine. I don't think we need to keep different set of properties for asimba... it should always match oxauth.

**Comment by dmogn** [comment]
oxasimba-ldap.properties - for back compatibility only.

**Comment by dmogn** [comment]
Done.

**Comment by yurem** [comment]
yes, we decided to keep oxasimba-ldap.properties for special case when it uses another server or we need to override some ldap properties.

Workflow now looks like:
if (check if there is oxasimba-ldap.properties) {
load config from oxasimba-ldap.properties
} else {
load config from ox-ldap.properties
}

Now 3 applications reads config from ox-ldap.properties: oxIdp, oxCas, oxAsimba
