### ISSUE TITLE
Can't add remote IDP / SP

### ISSUE THREAD

**Issue by mzico** [GluuFederation/gluu-Asimba#13]
(a) Problem: Unable to add remote IDP/SP with oxTrust. 
(b) Gluu Server version: Gluu Server 2.4.3 beta3 
     (i) oxAuth Implementation Version: 2.4.3.Final
     (ii) oxAuth Implementation Build: 18f82c7188c229a340950df3723e9fd80aadff35
     (iii) oxTrust Implementation Version: 2.4.3.Final
     (iv) oxTrust Implementation-Build: e25ae

(c) Stack trace: ldap information is not right. Most probably syntax error _....entry o=gluu!CCDF.8850.AF32.E031. .....:_ 

`2016-04-17 14:37:18,776 ERROR [org.jboss.seam.exception.Exceptions] handled and logged exception
javax.servlet.ServletException: org.gluu.site.ldap.persistence.exception.EntryPersistenceException: Failed to persist entry: inum=o=@!3980.B47A.4049.D66D!0001!DE71                                                                     .B89F,o=gluu!CCDF.8850.AF32.E031.49CD.D7F3.1693.BB7F,ou=requestors,ou=oxasimba,o=@!3980.B47A.4049.D66D!0001!DE71.B89F,o=gluu
        at javax.faces.webapp.FacesServlet.service(FacesServlet.java:606)
......
......
Caused by: org.gluu.site.ldap.persistence.exception.EntryPersistenceException: Failed to persist entry: inum=o=@!3980.B47A.4049.D66D!0001!DE71.B89F,o=gluu!CCDF.885                                                                     0.AF32.E031.49CD.D7F3.1693.BB7F,ou=requestors,ou=oxasimba,o=@!3980.B47A.4049.D66D!0001!DE71.B89F,o=gluu`

(d) How to reproduce: 

Install 2.4.3 beta4 and try to use 'Asimba' feature from oxTrust

**Comment by dmogn** [comment]
Fixed.

**Comment by mchagas** [comment]
Hi guys, how can I update my Gluu CE 2.4.3 to resolve this bug with Asimba? I tried to add trust relationships and gets the same error.

**Comment by xupetao** [comment]
@mchagas I think you are a xupeta

**Comment by dmogn** [comment]
Hi, @mchagas.

You can replace /opt/gluu-server-2.4.3/opt/apache-tomcat-7.0.65/webapps/asimba.war file with
http://ox.gluu.org/maven/org/asimba/asimba-wa/2.4.3.Final/asimba-wa-2.4.3.Final.war
and
/opt/gluu-server-2.4.3/opt/apache-tomcat-7.0.65/webapps/identity.war file with
https://ox.gluu.org/maven/org/xdi/oxtrust-server/2.4.3.Final/oxtrust-server-2.4.3.Final.war
Then backup config files from webapps/asimba dir and remove asimba and idenity dirs (Tomcat will recreates those).

**Comment by nynymike** [comment]
@mchagas - Please create an account on https://support.gluu.org and post questions about the Gluu Server CE there. github is not a forum for support on the Gluu Server.

**Comment by mchagas** [comment]
Hi, @dmogn and @nynymike. I'll do this. Register and post my questions on Gluu Support Forum. Thanks for advice.
