### ISSUE TITLE
Allow to change the order of the IDPs via the GUI

### ISSUE THREAD

**Issue by dmogn** [GluuFederation/gluu-Asimba#23]
Deadline: end of August

**Comment by dmogn** [comment]
Done.

**Comment by mzico** [comment]
@dmogn : Which oxTrust version has this feature? I tried 2.4.5-snapshot but seems like it's not working and breaking IDP because it has Shib v3 inside of it.

**Comment by dmogn** [comment]
https://github.com/GluuFederation/oxTrust/issues/397

**Comment by dmogn** [comment]
@mzico  - Yuriy added it to SP3, but SP3 WAR has not been rebuilded...
http://ox.gluu.org/maven/org/xdi/oxtrust-server/2.4.4.sp3/
https://github.com/GluuFederation/oxTrust/issues/397

**Comment by mzico** [comment]
Thanks @dmogn , I'll wait for @yurem to build sp3 then.

**Comment by mzico** [comment]
@dmogn @yurem : Asimba oxTrust feature working in SP3. I applied oxTrust sp3 on a 2.4.4 SP2 instance. 
Thanks for your help on this. We will move forward for customer now.
