### ISSUE TITLE
Asimba does not logout (a session still exists in memory storage)

### ISSUE THREAD

**Issue by dmogn** [GluuFederation/gluu-Asimba#25]
Asimba should not store sessions. This can only cause problems with logout.

**Comment by dmogn** [comment]
Done.

**Comment by nynymike** [comment]
three cheers !

**Comment by mzico** [comment]
@dmogn : Is it possible to implement this in one 2.4.4 server?

**Comment by dmogn** [comment]
@mzico - Yes.

**Comment by mzico** [comment]
@dmogn : great! links?

**Comment by dmogn** [comment]
2.4.4 SP3
3.0.0
