### ISSUE TITLE
Update opensaml dependency to latest version

### ISSUE THREAD

**Issue by dmogn** [GluuFederation/gluu-Asimba#27]
Related with #26.
Maybe latest opensaml version has more parsing capabilities for unusual attributes, like google IDP.

**Comment by nynymike** [comment]
What makes these attributes unusual?

**Comment by mzico** [comment]
@nynymike : https://support.gluu.org/identity-management/google-idp-custom-attributes-seem-to-trigger-500-server-error-from-asimba-3260/

**Comment by dmogn** [comment]
@nynymike  opensame cannot parse/extract attr value in this case.
We should switch to latest opensaml version before next steps, I think.

**Comment by dmogn** [comment]
opensaml does not show errors, but parse empty attr value

**Comment by dmogn** [comment]
Current dependency version: 2.6.1 
Latest V2: 2.6.4
V2 branch support discontinued at july 2016.
The current stable release is 3.2.0

**Comment by dmogn** [comment]
It will be big change, because of API difference. But opnsaml v2 is obsolete and unsupported, so we need do it.

**Comment by nynymike** [comment]
Note from Mark Dobrinic:
```
Only thing I remember is when going from OpenSAML 2.5.x to 2.6.x, there was this thing with the MetadataProviders, taking a thread per provider. That was quite some thing to integrate.`
```
