### ISSUE TITLE
Make some way for attribute (claims) mapping

### ISSUE THREAD

**Issue by dmogn** [GluuFederation/gluu-Asimba#3]
Mike Schwartz: One question:
Mike Schwartz: claims mapping....
Mike Schwartz: let's say inbound an IDP has one attribute
Mike Schwartz: but we'd like to change the name of that attribute.
Mike Schwartz: can it be done on a per IDP basis?

Mike Schwartz: So the interface for claims mapping ...
Mike Schwartz: Source  ... Destination
<saml URI for attr>    <saml URI for attr>
Mike Schwartz: something like that ?

Mike Schwartz: For example, let's say I have an attribute with SAML URI (in source IDP)
Mike Schwartz: "urn:oid:locale-oid"
Mike Schwartz: and I want to map it to attribute (in local Shibboleth SAML IDP)
Mike Schwartz: "urn:oid:city-oid"

Dmitry Ogn: Here at the bottom: http://sourceforge.net/p/asimba/wiki/Application%20level%20architecture/
Core components:
...
attribute-gatherer 	the profile that will collect the attributes of an authenticated user
attribute-release 	the profile that decides which attributes can be released in a response to an identity request
...
- attribute converter is dedicated module by the architecture.

Mike Schwartz: I don't see attribute converter...
Dmitry Ogn: It is my comment. I think attribute-gatherer + attribute-release = converter

Dmitry Ogn: There are attributes in SP's and IDP's NameID section: http://sourceforge.net/p/asimba/wiki/saml2-nameid/
But it is not mapping.

Mike Schwartz: I think it would be configuration of the IDP...
Mike Schwartz: perhaps it could be implemented in the attribute gatherer...
Mike Schwartz: you might gather attr1, but map it to attr2 ....
Mike Schwartz: ok, at least I know what is the current capability
Mike Schwartz: I was not sure how to represent
Mike Schwartz: to customers the strategy

Dmitry Ogn: There is set of hard written attr format handlers: Default, Google-  MSO365- specific:
https://github.com/GluuFederation/gluu-Asimba/tree/master/asimba-saml2-utility/src/main/java/org/asimba/util/saml2/nameid/handler
Dmitry Ogn: We could add some custom mapper utility here in next versions and get per IDP/ per SP mapping feature.
Mike Schwartz: Yes, why don't you create an issue on this in Github
Mike Schwartz: Just to record the details of this conversation.
Dmitry Ogn: Ok, I'll

**Comment by dmogn** [comment]
There are 2 ways for attribute mapping:
- Hard code way for IDP: write a new handler class (examples in org/asimba/util/saml2/nameid/handler ).
- Soft way for SP: create new attribute-release profile; create new separated RequestorPool; select  the attribute-release profile name in attributeReleasePolicyID field of the RequestorPool.

So, we need some GUI for attribute-release profile and possibly some universal attribute handler + GUI for IDP side.

**Comment by nynymike** [comment]
Also, a common pattern in the Gluu Server is to use an Jython "interception script"

**Comment by nynymike** [comment]
I think this mapping can be handled in the Gluu Sever custom auth script.
