### ISSUE TITLE
Create 'saml.pem' inside /etc/certs/

### ISSUE THREAD

**Issue by mzico** [GluuFederation/gluu-Asimba#33]
I think it will be good if 'saml.pem' cert is created automatically if user select asimba during setup.py run. 

'saml.pem' contains the ingrediant of 'asimba.crt'. Permission would be tomcat:tomcat 

It's not deadly urgent and is okay to push this enhancement for 3.1. I don't see any 3.1 milestone here so keeping 'Milestone' blank.

**Comment by dmogn** [comment]
>> 'saml.pem' contains the ingrediant of 'asimba.crt'.

@mzico  Maybe, name it 'asimba.pem'?

**Comment by mzico** [comment]
@dmogn : If Custom script 'asimba' has no issue on such naming; fine with us. 
Please talk a bit with Movchan for this custom script to know if there is any restriction on naming this cert or not.

**Comment by dmogn** [comment]
Done.
