### ISSUE TITLE
An Asimba setting which controls the number of seconds after which Asimba refuses authentication based on AuthInstant

### ISSUE THREAD

**Issue by dmogn** [GluuFederation/gluu-Asimba#44]
Because both we and our users are currently getting surprised by Asimba denying any ADFS user who authenticated to ADFS more than an hour before they passed through Asimba.

As far as I can see, the number of seconds is hard-coded to 1 hour in Asimba.

This part is pretty urgent for us. Nobody likes surprises and none of our other timeouts are as short as 1 hour.

**Comment by willow9886** [comment]
@dmogn did this make it into the 3.1.1 final packages?

**Comment by willow9886** [comment]
@dmogn did this make it into the 3.1.1 final packages?

**Comment by mzico** [comment]
@dmogn : anything?

**Comment by dmogn** [comment]
https://github.com/GluuFederation/community-edition-setup/blob/master/templates/asimba.xml#L67
I've documented session expiration-related fields.

TODO: remove hardcoded 1-hour expiration (load from XML configuration)
https://github.com/GluuFederation/gluu-Asimba/blob/master/asimba-am-remote-saml2/src/main/java/com/alfaariss/oa/authentication/remote/saml2/BaseSAML2AuthenticationMethod.java#L287-L288

**Comment by dmogn** [comment]
Upd. all Ok - SAML2 TimestampWindow is configured here in default settings:
https://github.com/GluuFederation/community-edition-setup/blob/master/templates/asimba.xml#L165
