### ISSUE TITLE
Failed to start asimba after CE install

### ISSUE THREAD

**Issue by yurem** [GluuFederation/gluu-Asimba#7]
After CE 2.4.2 beta2 install asimba is not starting.

javax.servlet.ServletException: 0001

at com.alfaariss.oa.sso.web.WebSSOServlet.init(WebSSOServlet.java:136) at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1284) at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1197)

**Comment by yurem** [comment]
I think the problem caused by wrong asimba.xml template in setup:
https://github.com/GluuFederation/community-edition-setup/blob/master/templates/asimba.xml
https://github.com/GluuFederation/community-edition-setup/blob/master/templates/asimba.properties

We need to fix these templates before issue 2.4.2

**Comment by yurem** [comment]
@nynymike

**Comment by dmogn** [comment]
As told me Yury - the tempate file is very old and has roots in Asimba 1.2... vesions.

Our goal:
1. More modern "pure XML" tempate file.
2. The tempate with removed "XML-configuration" modules and replaced by "LDAP-configuration".

We have 3 candidates:
1. Template file from our setup (Asimba 1.2 ...)
2. Default XML from Asimba 1.3.1 sources
3. I have a test vesion with configured local Shib SP.

**Comment by dmogn** [comment]
https://github.com/GluuFederation/community-edition-setup/blob/master/templates/asimba.properties
- this file is Ok.

**Comment by nynymike** [comment]
I have no preference... pick the best solution.

**Comment by dmogn** [comment]
Review result: the template isn't obsolete. It's a customization with SAML-only method/profile enabled and SAML-only IDP as source, so Asimba works only as a SAML proxy (as we use it).
Deleted profiles:
GuestAuthenticationMethod - Login as guest
IdentifyingMethod - Login with provided username without authentication
AsimbaUsersXmlPassword - Login from Asimba userstore (password)
SMSCMAuthMethod - Login with SMS Authentication (CM gateway)
SMSCMAuthMethod - Login with Username/Password and SMS authentication (CM gateway)
Deleted protocols:
aselect 

None example uses JDBC features.

**Comment by dmogn** [comment]
(ASIMBAWA) [2016-02-28 19:01:34] [ERROR] SAML2AuthenticationMethod Configured class doesn't exist: org.gluu.authentication.remote.saml2.selector.ApplicationSelectorLDAP
java.lang.ClassNotFoundException: org.gluu.authentication.remote.saml2.selector.ApplicationSelectorLDAP
        at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1720)

- Something wrong in our Asimba build. This class should exist in asimba-wa.war classpath.

**Comment by yurem** [comment]
There is no problem with build. The re is problem in asimba-wa: [pom.xml](https://ox.gluu.org/maven/org/asimba/asimba-wa/2.4.2.Final/asimba-wa-2.4.2.Final.war)

If we are using this library in asimba-wa we need to add maven dependency:
  <dependency>
   <groupId>org.asimba</groupId>
   <artifactId>asimba-selector-ldap</artifactId>
   <version>${asimba.version}</version>

**Comment by dmogn** [comment]
Yeh, it's pom. Fixed.
