### ISSUE TITLE
[Bug][SAML->Asimba->IDPs] Clicking this accordion's link results in system error

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/gluu-Asimba#9]
Environment: Ubuntu 64bit 14.04.4 on VmWare Workstation 11.1.0 build-2496824, Gluu CE 2.4.2-2-BETA4

Steps to reproduce:
1) Log in to oxTrust as administrator
2) Move to the "SAML->Asimba->IDPs" page by clicking the corresponding link in the accordion menu

Result:
System error message appears and [a java error](https://github.com/GluuFederation/gluu-Asimba/files/162097/error.txt) is logged to wrapper.log

**Comment by dmogn** [comment]
This bug has been fixed in latest 2.4.2-1 final build.
